### ISSUE TITLE
POST params aren't passed when initiating search from a Multi-Account Container that doesn't allow the search URL

### ISSUE THREAD

**Issue by jn64** [andis-spr/duckduckgo-lite-search#1]
Sorry for the long report, but this need some background:

I use [Firefox Multi-Account Containers](https://addons.mozilla.org/en-GB/firefox/addon/multi-account-containers/). Individual containers have a setting called _Limit to designated sites_, which means any addresses not assigned to that container will open in a new, non-container tab (or the different container they're assigned to, if any).

For example, I have a _GitHub_ container, that only allows `github.com` addresses. While on a _GitHub_ container tab, if I click any links or type any address that isn't `github.com`, it will open in a new non-container tab. However, if I type a search term and search DDG Lite using this add-on from such a container, a new tab opens with the address `https://lite.duckduckgo.com/lite/`, but it seems like the search query isn't passed.

(This add-on works fine from containers where _Limit to designated sites_ is disabled—the search would simply open in the current container tab.)

I believe this is https://github.com/mozilla/multi-account-containers/issues/1886, but there is a possible workaround on the search add-on's side, which is why I'm opening an issue here.

## Workaround

I only tested briefly, but it seems like putting the search terms in the URL instead of POST works in the above situation:

```patch
--- manifest.json
+++ manifest.json
@@ -14,8 +14,7 @@
     "chrome_settings_overrides": {
         "search_provider": {
             "name": "DuckDuckGo Lite",
-            "search_url": "https://lite.duckduckgo.com/lite/",
-            "search_url_post_params": "q={searchTerms}",
+            "search_url": "https://lite.duckduckgo.com/lite/?q={searchTerms}",
             "keyword": "ddg",
             "favicon_url": "https://duckduckgo.com/favicon.ico",
             "is_default": true,
```

The drawback is that search queries would be visible in the browser history, which might not be desirable to you or existing users.

If you're ok with it, I'll do a PR (after a bit more testing). Or if you have any other ideas on how to solve this problem. I'm not familiar with WebExtension so I might be missing something—maybe providing 2 different search options from one add-on is possible? one POST, one URL. Worst case, it could be a separate add-on.

**Comment by andis-sprinkis** [comment]
@jn64 , sorry, by some weird happenstance I did not see any notifications of this GitHub Issue being created back in December.

I am OK with switching the default method to GET for this extension.

I'll look into this a bit later.

**Comment by andis-sprinkis** [comment]
Doesn't seem like a generic search provider WebExtension can support multiple request methods in one extension.

I have submitted a new version of the existing extension, switching it to use the HTTP GET method.

I also have also submitted an HTTP POST request variant of this search provider as a [separate extension](https://addons.mozilla.org/en-US/firefox/addon/ddg-lite-search-provider-post/) on Firefox Add-ons site. Should be approved and available soon.

**Comment by jn64** [comment]
Thanks! Tested the update, works as expected with containers.

Firefox 112.0.1
Firefox Multi-Account Containers	extension	8.1.2
DuckDuckGo Lite Search	extension	2.0
