### ISSUE TITLE
Bad colour when using dark reader with duckduckgo lite.

### ISSUE THREAD

**Issue by ghost** [andis-spr/duckduckgo-lite-search#2]
I can't see words when using dark reader.

**Comment by andis-sprinkis** [comment]
You may want to reach out to "dark reader" maintainers about that.

The browser extension in this repository only provides a way to run DuckDuckGo Lite search engine queries from the web browser UI. It does not serve or alter the DuckDuckGo Lite search engine pages.
Also, I am not responsible for the DuckDuckGo Lite search engine pages or associated with the DuckDuckGo company.
